# Generated by Django 4.2.6 on 2023-11-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affectApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
    ]
