# Generated by Django 4.2.6 on 2023-11-24 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("affectApp", "0002_faceimages_delete_hotel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FaceImages",
            new_name="FaceImage",
        ),
    ]
