# Generated by Django 4.2.6 on 2023-11-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affectApp", "0003_rename_faceimages_faceimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="faceimage",
            name="name",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
